const curatedArtworks = [
  {
    id: "van-gogh-straw-hat",
    title: "Self-Portrait with a Straw Hat",
    artist: "Vincent van Gogh",
    year: "1887",
    movement: "Post-Impressionism",
    museum: "The Metropolitan Museum of Art",
    museumCode: "met",
    previewUrl: "https://images.metmuseum.org/CRDImages/ep/web-large/DP-21132-001.jpeg",
    downloadUrl: "https://images.metmuseum.org/CRDImages/ep/original/DP-21132-001.jpg",
    originalUrl: "https://www.metmuseum.org/art/collection/search/436532"
  },
  {
    id: "van-gogh-wheatfield-cypresses",
    title: "Wheatfield with Cypresses",
    artist: "Vincent van Gogh",
    year: "1889",
    movement: "Post-Impressionism",
    museum: "The Metropolitan Museum of Art",
    museumCode: "met",
    previewUrl: "https://images.metmuseum.org/CRDImages/ep/web-large/DP130965.jpeg",
    downloadUrl: "https://images.metmuseum.org/CRDImages/ep/original/DP130965.jpg",
    originalUrl: "https://www.metmuseum.org/art/collection/search/436535"
  },
  {
    id: "monet-water-lilies-met",
    title: "Bridge over a Pond of Water Lilies",
    artist: "Claude Monet",
    year: "1899",
    movement: "Impressionism",
    museum: "The Metropolitan Museum of Art",
    museumCode: "met",
    previewUrl: "https://images.metmuseum.org/CRDImages/ep/web-large/DP-19542-001.jpeg",
    downloadUrl: "https://images.metmuseum.org/CRDImages/ep/original/DP-19542-001.jpg",
    originalUrl: "https://www.metmuseum.org/art/collection/search/437127"
  },
  {
    id: "monet-parc-monceau",
    title: "The Parc Monceau",
    artist: "Claude Monet",
    year: "1878",
    movement: "Impressionism",
    museum: "The Metropolitan Museum of Art",
    museumCode: "met",
    previewUrl: "https://images.metmuseum.org/CRDImages/ep/web-large/DP-21473-001.jpeg",
    downloadUrl: "https://images.metmuseum.org/CRDImages/ep/original/DP-21473-001.jpg",
    originalUrl: "https://www.metmuseum.org/art/collection/search/437122"
  },
  {
    id: "hokusai-great-wave-met",
    title: "Under the Wave off Kanagawa (The Great Wave)",
    artist: "Katsushika Hokusai",
    year: "ca. 1830–32",
    movement: "Ukiyo-e",
    museum: "The Metropolitan Museum of Art",
    museumCode: "met",
    previewUrl: "https://images.metmuseum.org/CRDImages/as/web-large/DP130155.jpeg",
    downloadUrl: "https://images.metmuseum.org/CRDImages/as/original/DP130155.jpg",
    originalUrl: "https://www.metmuseum.org/art/collection/search/45434"
  },
  {
    id: "vermeer-young-woman-met",
    title: "Study of a Young Woman",
    artist: "Johannes Vermeer",
    year: "ca. 1665–67",
    movement: "Baroque",
    museum: "The Metropolitan Museum of Art",
    museumCode: "met",
    previewUrl: "https://images.metmuseum.org/CRDImages/ep/web-large/DP-14631-001.jpeg",
    downloadUrl: "https://images.metmuseum.org/CRDImages/ep/original/DP-14631-001.jpg",
    originalUrl: "https://www.metmuseum.org/art/collection/search/437879"
  },
  {
    id: "seurat-circus-sideshow",
    title: "Circus Sideshow (Parade de cirque)",
    artist: "Georges Seurat",
    year: "1887–88",
    movement: "Post-Impressionism",
    museum: "The Metropolitan Museum of Art",
    museumCode: "met",
    previewUrl: "https://images.metmuseum.org/CRDImages/ep/web-large/DP-14286-015.jpeg",
    downloadUrl: "https://images.metmuseum.org/CRDImages/ep/original/DP-14286-015.jpg",
    originalUrl: "https://www.metmuseum.org/art/collection/search/437654"
  },
  {
    id: "cole-oxbow",
    title: "The Oxbow (View from Mount Holyoke)",
    artist: "Thomas Cole",
    year: "1836",
    movement: "Landscape",
    museum: "The Metropolitan Museum of Art",
    museumCode: "met",
    previewUrl: "https://images.metmuseum.org/CRDImages/ep/web-large/DP143194.jpeg",
    downloadUrl: "https://images.metmuseum.org/CRDImages/ep/original/DP143194.jpg",
    originalUrl: "https://www.metmuseum.org/art/collection/search/10497"
  },
  {
    id: "sargent-madame-x",
    title: "Madame X (Madame Pierre Gautreau)",
    artist: "John Singer Sargent",
    year: "1883–84",
    movement: "Realism",
    museum: "The Metropolitan Museum of Art",
    museumCode: "met",
    previewUrl: "https://images.metmuseum.org/CRDImages/ag/web-large/DP-14286-091.jpeg",
    downloadUrl: "https://images.metmuseum.org/CRDImages/ag/original/DP-14286-091.jpg",
    originalUrl: "https://www.metmuseum.org/art/collection/search/12127"
  },
  {
    id: "seurat-sunday-grand-jatte",
    title: "A Sunday on La Grande Jatte — 1884",
    artist: "Georges Seurat",
    year: "1884–86",
    movement: "Post-Impressionism",
    museum: "Art Institute of Chicago",
    museumCode: "chicago",
    previewUrl: "https://www.artic.edu/iiif/2/25f22d71-1b8a-4ab0-0e2d-3d4a2b2e8d2e/full/843,/0/default.jpg",
    downloadUrl: "https://www.artic.edu/iiif/2/25f22d71-1b8a-4ab0-0e2d-3d4a2b2e8d2e/full/4000,/0/default.jpg",
    originalUrl: "https://www.artic.edu/collection/artworks/27992"
  },
  {
    id: "van-gogh-bedroom-chicago",
    title: "The Bedroom",
    artist: "Vincent van Gogh",
    year: "1889",
    movement: "Post-Impressionism",
    museum: "Art Institute of Chicago",
    museumCode: "chicago",
    previewUrl: "https://www.artic.edu/iiif/2/3c27b49f-8777-a9d7-85be-c2475f1a3d07/full/843,/0/default.jpg",
    downloadUrl: "https://www.artic.edu/iiif/2/3c27b49f-8777-a9d7-85be-c2475f1a3d07/full/4000,/0/default.jpg",
    originalUrl: "https://www.artic.edu/collection/artworks/28560"
  },
  {
    id: "monet-water-lilies-chicago",
    title: "Water Lilies",
    artist: "Claude Monet",
    year: "1906",
    movement: "Impressionism",
    museum: "Art Institute of Chicago",
    museumCode: "chicago",
    previewUrl: "https://www.artic.edu/iiif/2/1b13dd45-4228-dd66-e822-777bc3dbbe95/full/843,/0/default.jpg",
    downloadUrl: "https://www.artic.edu/iiif/2/1b13dd45-4228-dd66-e822-777bc3dbbe95/full/4000,/0/default.jpg",
    originalUrl: "https://www.artic.edu/collection/artworks/16571"
  },
  {
    id: "wood-american-gothic",
    title: "American Gothic",
    artist: "Grant Wood",
    year: "1930",
    movement: "Realism",
    museum: "Art Institute of Chicago",
    museumCode: "chicago",
    previewUrl: "https://www.artic.edu/iiif/2/14e21a22-263a-7a5f-46ea-017e66df98b0/full/843,/0/default.jpg",
    downloadUrl: "https://www.artic.edu/iiif/2/14e21a22-263a-7a5f-46ea-017e66df98b0/full/4000,/0/default.jpg",
    originalUrl: "https://www.artic.edu/collection/artworks/6565"
  },
  {
    id: "hopper-nighthawks",
    title: "Nighthawks",
    artist: "Edward Hopper",
    year: "1942",
    movement: "Realism",
    museum: "Art Institute of Chicago",
    museumCode: "chicago",
    previewUrl: "https://www.artic.edu/iiif/2/5f8c6cf6-0043-4ccb-b0b3-96b02662c1d3/full/843,/0/default.jpg",
    downloadUrl: "https://www.artic.edu/iiif/2/5f8c6cf6-0043-4ccb-b0b3-96b02662c1d3/full/4000,/0/default.jpg",
    originalUrl: "https://www.artic.edu/collection/artworks/111622"
  },
  {
    id: "vermeer-milkmaid-rijks",
    title: "The Milkmaid",
    artist: "Johannes Vermeer",
    year: "ca. 1660",
    movement: "Baroque",
    museum: "Rijksmuseum",
    museumCode: "rijksmuseum",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Johannes_Vermeer_-_The_Milkmaid_-_Google_Art_Project.jpg/1024px-Johannes_Vermeer_-_The_Milkmaid_-_Google_Art_Project.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/2/20/Johannes_Vermeer_-_The_Milkmaid_-_Google_Art_Project.jpg",
    originalUrl: "https://www.rijksmuseum.nl/en/collection/SK-A-2344"
  },
  {
    id: "rembrandt-night-watch",
    title: "The Night Watch",
    artist: "Rembrandt van Rijn",
    year: "1642",
    movement: "Baroque",
    museum: "Rijksmuseum",
    museumCode: "rijksmuseum",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/The_Nightwatch_by_Rembrandt_-_as_seen_on_the_exhibition_Rembrandt_-_Vel%C3%A1zquez.jpg/1024px-The_Nightwatch_by_Rembrandt_-_as_seen_on_the_exhibition_Rembrandt_-_Vel%C3%A1zquez.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/9/94/The_Nightwatch_by_Rembrandt_-_as_seen_on_the_exhibition_Rembrandt_-_Vel%C3%A1zquez.jpg",
    originalUrl: "https://www.rijksmuseum.nl/en/collection/SK-C-5"
  },
  {
    id: "van-gogh-grey-hat-rijks",
    title: "Self-Portrait with Grey Felt Hat",
    artist: "Vincent van Gogh",
    year: "1887",
    movement: "Post-Impressionism",
    museum: "Rijksmuseum",
    museumCode: "rijksmuseum",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Vincent_van_Gogh_-_Self-Portrait_with_Grey_Felt_Hat_-_Google_Art_Project.jpg/1024px-Vincent_van_Gogh_-_Self-Portrait_with_Grey_Felt_Hat_-_Google_Art_Project.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Vincent_van_Gogh_-_Self-Portrait_with_Grey_Felt_Hat_-_Google_Art_Project.jpg",
    originalUrl: "https://www.rijksmuseum.nl/en/collection/SK-A-3262"
  },
  {
    id: "steen-saint-nicholas",
    title: "The Feast of Saint Nicholas",
    artist: "Jan Steen",
    year: "ca. 1665–68",
    movement: "Baroque",
    museum: "Rijksmuseum",
    museumCode: "rijksmuseum",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Jan_Steen_-_The_Feast_of_Saint_Nicholas_-_Google_Art_Project.jpg/1024px-Jan_Steen_-_The_Feast_of_Saint_Nicholas_-_Google_Art_Project.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Jan_Steen_-_The_Feast_of_Saint_Nicholas_-_Google_Art_Project.jpg",
    originalUrl: "https://www.rijksmuseum.nl/en/collection/SK-A-385"
  },
  {
    id: "monet-parasol-nga",
    title: "Woman with a Parasol - Madame Monet and Her Son",
    artist: "Claude Monet",
    year: "1875",
    movement: "Impressionism",
    museum: "National Gallery of Art, Washington D.C.",
    museumCode: "nga",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Claude_Monet_-_Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son_-_Google_Art_Project.jpg/1024px-Claude_Monet_-_Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son_-_Google_Art_Project.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Claude_Monet_-_Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son_-_Google_Art_Project.jpg",
    originalUrl: "https://www.nga.gov/collection/art-object-page.61250.html"
  },
  {
    id: "da-vinci-ginevra-nga",
    title: "Ginevra de' Benci",
    artist: "Leonardo da Vinci",
    year: "ca. 1474/1478",
    movement: "Renaissance",
    museum: "National Gallery of Art, Washington D.C.",
    museumCode: "nga",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Leonardo_da_Vinci_-_Ginevra_de%27_Benci_-_Google_Art_Project.jpg/1024px-Leonardo_da_Vinci_-_Ginevra_de%27_Benci_-_Google_Art_Project.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Leonardo_da_Vinci_-_Ginevra_de%27_Benci_-_Google_Art_Project.jpg",
    originalUrl: "https://www.nga.gov/collection/art-object-page.50724.html"
  },
  {
    id: "van-gogh-portrait-1889-nga",
    title: "Self-Portrait (1889)",
    artist: "Vincent van Gogh",
    year: "1889",
    movement: "Post-Impressionism",
    museum: "National Gallery of Art, Washington D.C.",
    museumCode: "nga",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg/1024px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/7/71/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg",
    originalUrl: "https://www.nga.gov/collection/art-object-page.106382.html"
  },
  {
    id: "degas-dance-class-nga",
    title: "The Dance Class",
    artist: "Edgar Degas",
    year: "ca. 1873",
    movement: "Impressionism",
    museum: "National Gallery of Art, Washington D.C.",
    museumCode: "nga",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Edgar_Degas_-_The_Dance_Class_-_Google_Art_Project.jpg/1024px-Edgar_Degas_-_The_Dance_Class_-_Google_Art_Project.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Edgar_Degas_-_The_Dance_Class_-_Google_Art_Project.jpg",
    originalUrl: "https://www.nga.gov/collection/art-object-page.51178.html"
  },
  {
    id: "van-gogh-irises-getty",
    title: "Irises",
    artist: "Vincent van Gogh",
    year: "1889",
    movement: "Post-Impressionism",
    museum: "J. Paul Getty Museum",
    museumCode: "getty",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Irises-Vincent_van_Gogh.jpg/1024px-Irises-Vincent_van_Gogh.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Irises-Vincent_van_Gogh.jpg",
    originalUrl: "https://www.getty.edu/art/collection/object/103J7M"
  },
  {
    id: "manet-jeanne-getty",
    title: "Jeanne (Spring)",
    artist: "Édouard Manet",
    year: "1881",
    movement: "Impressionism",
    museum: "J. Paul Getty Museum",
    museumCode: "getty",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/%C3%89douard_Manet_-_Jeanne_%28Spring%29.jpg/1024px-%C3%89douard_Manet_-_Jeanne_%28Spring%29.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2f/%C3%89douard_Manet_-_Jeanne_%28Spring%29.jpg",
    originalUrl: "https://www.getty.edu/art/collection/object/109CDQ"
  },
  {
    id: "monet-rouen-cathedral-getty",
    title: "The Portal of Rouen Cathedral in Morning Light",
    artist: "Claude Monet",
    year: "1894",
    movement: "Impressionism",
    museum: "J. Paul Getty Museum",
    museumCode: "getty",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Claude_Monet_-_The_Portal_of_Rouen_Cathedral_in_Morning_Light_-_Google_Art_Project.jpg/1024px-Claude_Monet_-_The_Portal_of_Rouen_Cathedral_in_Morning_Light_-_Google_Art_Project.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/3/32/Claude_Monet_-_The_Portal_of_Rouen_Cathedral_in_Morning_Light_-_Google_Art_Project.jpg",
    originalUrl: "https://www.getty.edu/art/collection/object/103RE9"
  },
  {
    id: "da-vinci-mona-lisa",
    title: "Mona Lisa",
    artist: "Leonardo da Vinci",
    year: "1503–1519",
    movement: "Renaissance",
    museum: "Musée du Louvre, Paris",
    museumCode: "other",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/1024px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
    originalUrl: "https://collections.louvre.fr/en/ark:/53355/cl010062370"
  },
  {
    id: "botticelli-birth-venus",
    title: "The Birth of Venus",
    artist: "Sandro Botticelli",
    year: "ca. 1485",
    movement: "Renaissance",
    museum: "Uffizi Gallery, Florence",
    museumCode: "other",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project.jpg/1024px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project.jpg",
    originalUrl: "https://www.uffizi.it/en/artworks/birth-of-venus"
  },
  {
    id: "friedrich-wanderer-fog",
    title: "Wanderer above the Sea of Fog",
    artist: "Caspar David Friedrich",
    year: "ca. 1818",
    movement: "Landscape",
    museum: "Hamburger Kunsthalle, Germany",
    museumCode: "other",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/1024px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg",
    originalUrl: "https://online-sammlung.hamburger-kunsthalle.de/de/objekt/HK-5161"
  },
  {
    id: "klimt-the-kiss",
    title: "The Kiss (Der Kuss)",
    artist: "Gustav Klimt",
    year: "1907–1908",
    movement: "Modernism",
    museum: "Österreichische Galerie Belvedere, Vienna",
    museumCode: "other",
    previewUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Art_Project.jpg/1024px-The_Kiss_-_Gustav_Klimt_-_Google_Art_Project.jpg",
    downloadUrl: "https://upload.wikimedia.org/wikipedia/commons/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Art_Project.jpg",
    originalUrl: "https://sammlung.belvedere.at/objects/10578/der-kuss"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { curatedArtworks };
}
